/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Event */
        post: operations["record_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Question */
        post: operations["ask_question_api_v1_qa_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Resource */
        post: operations["import_resource_api_v1_resources_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessLevel
         * @enum {string}
         */
        AccessLevel: "public" | "course" | "private";
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Course Id */
            course_id: string;
            /** Knowledge Point Ids */
            knowledge_point_ids?: string[];
            /** Question */
            question: string;
            /** Resource Ids */
            resource_ids?: string[];
            /** Task Id */
            task_id?: string | null;
            /** User Id */
            user_id: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Confidence */
            confidence: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Mode
             * @default offline
             * @enum {string}
             */
            mode: "offline" | "external";
            /** Request Id */
            request_id: string;
        };
        /** ChunkMetadata */
        ChunkMetadata: {
            access_level: components["schemas"]["AccessLevel"];
            /** Chapter */
            chapter: string;
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            content_type: components["schemas"]["ContentType"];
            /** Knowledge Point Ids */
            knowledge_point_ids: string[];
            language: components["schemas"]["Language"];
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Resource Id */
            resource_id: string;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
        };
        /** Citation */
        Citation: {
            /** Chapter */
            chapter: string;
            /** Chunk Id */
            chunk_id: string;
            /** Citation Id */
            citation_id: string;
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            /** Quote */
            quote: string;
            /** Rerank Score */
            rerank_score?: number | null;
            /** Resource Id */
            resource_id: string;
            /** Retrieval Score */
            retrieval_score?: number | null;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
        };
        /**
         * ContentType
         * @enum {string}
         */
        ContentType: "pdf" | "ppt" | "subtitle" | "text" | "rfc" | "other";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "qa_asked" | "task_opened" | "task_completed" | "feedback_submitted";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Mode */
            mode: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        JsonValue: unknown;
        /**
         * Language
         * @enum {string}
         */
        Language: "zh" | "en" | "bilingual";
        /** LearningEvent */
        LearningEvent: {
            /** Course Id */
            course_id: string;
            /** Event Id */
            event_id: string;
            event_type: components["schemas"]["EventType"];
            /** Object Id */
            object_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** User Id */
            user_id: string;
        };
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "pending" | "parsed" | "failed";
        /** ResourceImportRequest */
        ResourceImportRequest: {
            content_type: components["schemas"]["ContentType"];
            /** Course Id */
            course_id: string;
            language: components["schemas"]["Language"];
            resource_type: components["schemas"]["ResourceType"];
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** ResourceImportResponse */
        ResourceImportResponse: {
            /** Error */
            error?: string | null;
            metadata?: components["schemas"]["ChunkMetadata"] | null;
            /** Resource Id */
            resource_id: string;
            sync_status: components["schemas"]["SyncStatus"];
        };
        /**
         * ResourceType
         * @enum {string}
         */
        ResourceType: "textbook" | "slide" | "lab_guide" | "video_subtitle" | "rfc" | "other";
        /**
         * SyncStatus
         * @enum {string}
         */
        SyncStatus: "accepted" | "completed" | "failed";
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "draft" | "published" | "completed";
        /** TaskTemplate */
        TaskTemplate: {
            /** Ai Feedback Points */
            ai_feedback_points: string[];
            /** Completion Criteria */
            completion_criteria: string[];
            /** Description */
            description: string;
            /** Knowledge Point Ids */
            knowledge_point_ids: string[];
            /** Prerequisite Ids */
            prerequisite_ids?: string[];
            /** Resource Ids */
            resource_ids: string[];
            status: components["schemas"]["TaskStatus"];
            /** Task Id */
            task_id: string;
            task_type: components["schemas"]["TaskType"];
            /** Title */
            title: string;
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "foundation" | "protocol_analysis" | "case_study" | "innovation_challenge" | "project_practice" | "troubleshooting";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    record_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask_question_api_v1_qa_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description 请求不符合接口契约 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    import_resource_api_v1_resources_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTemplate"][];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
