/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Events */
        get: operations["query_events_api_v1_events_get"];
        put?: never;
        /** Record Event */
        post: operations["record_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_api_v1_feedback_get"];
        put?: never;
        /** Create Feedback */
        post: operations["create_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback */
        get: operations["get_feedback_api_v1_feedback__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{feedback_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Feedback */
        patch: operations["review_feedback_api_v1_feedback__feedback_id__review_patch"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-base/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Changes */
        get: operations["list_changes_api_v1_knowledge_base_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-base/changes/{change_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Change */
        get: operations["get_change_api_v1_knowledge_base_changes__change_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Change
         * @description 推进或关闭知识库变更任务，完成知识库持续优化的闭环。
         */
        patch: operations["update_change_api_v1_knowledge_base_changes__change_id__patch"];
        trace?: never;
    };
    "/api/v1/knowledge-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Knowledge Points
         * @description 列出课程知识点，支持按章节或父知识点浏览知识图谱。
         */
        get: operations["list_knowledge_points_api_v1_knowledge_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-points/{knowledge_point_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Point */
        get: operations["get_knowledge_point_api_v1_knowledge_points__knowledge_point_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Question */
        post: operations["ask_question_api_v1_qa_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description 列出所有质量审查记录，可按 chunk_id 过滤。
         */
        get: operations["list_reviews_api_v1_quality_reviews_get"];
        put?: never;
        /**
         * Create Review
         * @description 创建质量审查记录。
         */
        post: operations["create_review_api_v1_quality_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description 获取单条质量审查记录。
         */
        get: operations["get_review_api_v1_quality_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Resources
         * @description 列出已导入的课程资料，便于确认解析结果是否入库。
         */
        get: operations["list_resources_api_v1_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Resource */
        post: operations["import_resource_api_v1_resources_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload And Parse
         * @description 上传课程文件，自动解析、切块、向量化入库。
         *
         *     支持 PDF、PPT（.pptx）、SRT 和 VTT 字幕文件。
         *     解析后的 Chunk 会存入 ChunkStore，并增量写入向量库，
         *     使新导入的资料可以立即被问答检索和引用。
         */
        post: operations["upload_and_parse_api_v1_resources_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{resource_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Resource Chunks
         * @description 读取某份资料解析出的全部 Chunk，用于人工核对切块与引用定位。
         */
        get: operations["list_resource_chunks_api_v1_resources__resource_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Publish Task */
        post: operations["publish_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Task Status
         * @description 在草稿、已发布和已完成之间流转任务状态。
         */
        patch: operations["update_task_status_api_v1_tasks__task_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessLevel
         * @enum {string}
         */
        AccessLevel: "public" | "course" | "private";
        /** AnswerFeedback */
        AnswerFeedback: {
            /** Answer */
            answer: string;
            /** Citation Ids */
            citation_ids?: string[];
            /** Course Id */
            course_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Feedback Id */
            feedback_id: string;
            /** Knowledge Base Change Id */
            knowledge_base_change_id?: string | null;
            /** Question */
            question: string;
            /** Reason */
            reason: string;
            /** Request Id */
            request_id: string;
            /**
             * Review Notes
             * @default
             */
            review_notes: string;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            status: components["schemas"]["FeedbackStatus"];
            /** User Id */
            user_id: string;
        };
        /** AnswerFeedbackCreate */
        AnswerFeedbackCreate: {
            /** Answer */
            answer: string;
            /** Citation Ids */
            citation_ids?: string[];
            /** Course Id */
            course_id: string;
            /** Question */
            question: string;
            /** Reason */
            reason: string;
            /** Request Id */
            request_id: string;
            /** User Id */
            user_id: string;
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Course Id */
            course_id: string;
            /** Knowledge Point Ids */
            knowledge_point_ids?: string[];
            /** Question */
            question: string;
            /** Resource Ids */
            resource_ids?: string[];
            /** Task Id */
            task_id?: string | null;
            /** User Id */
            user_id: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Confidence */
            confidence: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Mode
             * @default offline
             * @enum {string}
             */
            mode: "offline" | "external";
            /** Request Id */
            request_id: string;
        };
        /** Body_upload_and_parse_api_v1_resources_upload_post */
        Body_upload_and_parse_api_v1_resources_upload_post: {
            /**
             * Content Type
             * @description 文件类型：pdf/ppt/subtitle
             */
            content_type: string;
            /**
             * Course Id
             * @description 课程 ID
             */
            course_id: string;
            /**
             * File
             * @description 课程文件（PDF/PPT/SRT/VTT）
             */
            file: string;
            /**
             * Knowledge Point Ids
             * @description 知识点 ID，逗号分隔
             * @default
             */
            knowledge_point_ids: string;
            /**
             * Language
             * @description 语言：zh/en/bilingual
             * @default zh
             */
            language: string;
            /**
             * Title
             * @description 资料标题
             */
            title: string;
            /**
             * Version
             * @description 版本号
             * @default v1
             */
            version: string;
        };
        /** ChunkMetadata */
        ChunkMetadata: {
            access_level: components["schemas"]["AccessLevel"];
            /** Chapter */
            chapter: string;
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            content_type: components["schemas"]["ContentType"];
            extracted_content_type?: components["schemas"]["ContentType"] | null;
            /** Knowledge Point Ids */
            knowledge_point_ids: string[];
            language: components["schemas"]["Language"];
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Resource Id */
            resource_id: string;
            /** Source Path */
            source_path?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
        };
        /** Citation */
        Citation: {
            /** Chapter */
            chapter: string;
            /** Chunk Id */
            chunk_id: string;
            /** Citation Id */
            citation_id: string;
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            /** Quote */
            quote: string;
            /** Rerank Score */
            rerank_score?: number | null;
            /** Resource Id */
            resource_id: string;
            /** Retrieval Score */
            retrieval_score?: number | null;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
        };
        /**
         * ContentType
         * @enum {string}
         */
        ContentType: "pdf" | "ppt" | "subtitle" | "text" | "rfc" | "table" | "formula" | "image" | "diagram" | "other";
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "introductory" | "intermediate" | "advanced";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "qa_asked" | "task_opened" | "task_completed" | "feedback_submitted";
        /** FeedbackReviewRequest */
        FeedbackReviewRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /**
             * Review Notes
             * @default
             */
            review_notes: string;
            /** Reviewer */
            reviewer: string;
            /** Suggested Action */
            suggested_action?: string | null;
        };
        /**
         * FeedbackStatus
         * @enum {string}
         */
        FeedbackStatus: "pending_review" | "approved" | "rejected";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Mode */
            mode: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        JsonValue: unknown;
        /**
         * KnowledgeBaseChangeStatus
         * @enum {string}
         */
        KnowledgeBaseChangeStatus: "pending" | "in_progress" | "done" | "wont_fix";
        /** KnowledgeBaseChangeTask */
        KnowledgeBaseChangeTask: {
            /** Change Id */
            change_id: string;
            /** Course Id */
            course_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Feedback Id */
            feedback_id: string;
            /** Handler */
            handler?: string | null;
            /** Question */
            question: string;
            /** Reason */
            reason: string;
            /** Request Id */
            request_id: string;
            /**
             * Resolution Notes
             * @default
             */
            resolution_notes: string;
            /**
             * Resource Ids
             * @description 本次优化实际新增或修订的课程资料标识。
             */
            resource_ids?: string[];
            status: components["schemas"]["KnowledgeBaseChangeStatus"];
            /** Suggested Action */
            suggested_action: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * KnowledgeBaseChangeUpdateRequest
         * @description 推进或关闭知识库变更任务，构成“审核无效回答 → 优化知识库”的收尾环节。
         */
        KnowledgeBaseChangeUpdateRequest: {
            /** Handler */
            handler: string;
            /**
             * Resolution Notes
             * @default
             */
            resolution_notes: string;
            /** Resource Ids */
            resource_ids?: string[];
            status: components["schemas"]["KnowledgeBaseChangeStatus"];
        };
        /** KnowledgePoint */
        KnowledgePoint: {
            /** Chapter */
            chapter: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Keywords En */
            keywords_en?: string[];
            /** Keywords Zh */
            keywords_zh?: string[];
            /** Kind */
            kind: string;
            /** Knowledge Point Id */
            knowledge_point_id: string;
            /** Maintainer */
            maintainer: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Prerequisite Ids */
            prerequisite_ids?: string[];
            review_status: components["schemas"]["ReviewStatus"];
            /** Summary */
            summary: string;
        };
        /**
         * Language
         * @enum {string}
         */
        Language: "zh" | "en" | "bilingual";
        /** LearningEvent */
        LearningEvent: {
            /** Course Id */
            course_id: string;
            /** Event Id */
            event_id: string;
            event_type: components["schemas"]["EventType"];
            /** Object Id */
            object_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** User Id */
            user_id: string;
        };
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "pending" | "parsed" | "failed";
        /** QualityReview */
        QualityReview: {
            /** Chunk Id */
            chunk_id: string;
            /** Issues */
            issues?: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Resource Id */
            resource_id: string;
            /** Review Id */
            review_id: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Reviewer */
            reviewer: string;
            /** Score */
            score: number;
        };
        /** QualityReviewRequest */
        QualityReviewRequest: {
            /** Chunk Id */
            chunk_id: string;
            /** Issues */
            issues?: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Resource Id */
            resource_id: string;
            /** Reviewer */
            reviewer: string;
            /** Score */
            score: number;
        };
        /** ResourceImportRequest */
        ResourceImportRequest: {
            content_type: components["schemas"]["ContentType"];
            /** Course Id */
            course_id: string;
            language: components["schemas"]["Language"];
            resource_type: components["schemas"]["ResourceType"];
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** ResourceImportResponse */
        ResourceImportResponse: {
            /** Error */
            error?: string | null;
            metadata?: components["schemas"]["ChunkMetadata"] | null;
            /** Resource Id */
            resource_id: string;
            sync_status: components["schemas"]["SyncStatus"];
        };
        /**
         * ResourceSummary
         * @description 已导入资料的概览，用于确认解析与入库结果。
         */
        ResourceSummary: {
            /** Chunk Count */
            chunk_count: number;
            content_type: components["schemas"]["ContentType"];
            /** Course Id */
            course_id: string;
            language: components["schemas"]["Language"];
            /** Resource Id */
            resource_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
        };
        /**
         * ResourceType
         * @enum {string}
         */
        ResourceType: "textbook" | "slide" | "lab_guide" | "video_subtitle" | "rfc" | "other";
        /** ResourceUploadResponse */
        ResourceUploadResponse: {
            /** Chunk Count */
            chunk_count: number;
            /** Chunks */
            chunks?: components["schemas"]["ChunkMetadata"][];
            /** Error */
            error?: string | null;
            /** Filename */
            filename: string;
            /**
             * Indexed Chunks
             * @description 向量库在本次导入后的 Chunk 总数；为空表示未执行向量化。
             */
            indexed_chunks?: number | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Resource Id */
            resource_id: string;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "draft" | "reviewed" | "approved";
        /**
         * SyncStatus
         * @enum {string}
         */
        SyncStatus: "accepted" | "completed" | "failed";
        /** TaskPublishRequest */
        TaskPublishRequest: {
            /** Ai Feedback Points */
            ai_feedback_points: string[];
            /** Completion Criteria */
            completion_criteria: string[];
            /** Description */
            description: string;
            /** Knowledge Point Ids */
            knowledge_point_ids: string[];
            /** Prerequisite Ids */
            prerequisite_ids?: string[];
            /** Resource Ids */
            resource_ids: string[];
            /**
             * @description 发布状态；传 draft 可先存为草稿，稍后再发布。
             * @default published
             */
            status: components["schemas"]["TaskStatus"];
            /** Task Id */
            task_id: string;
            task_type: components["schemas"]["TaskType"];
            /** Title */
            title: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "draft" | "published" | "completed";
        /**
         * TaskStatusUpdateRequest
         * @description 任务状态流转请求，用于发布草稿或标记任务完成。
         */
        TaskStatusUpdateRequest: {
            status: components["schemas"]["TaskStatus"];
        };
        /** TaskTemplate */
        TaskTemplate: {
            /** Ai Feedback Points */
            ai_feedback_points: string[];
            /** Completion Criteria */
            completion_criteria: string[];
            /** Description */
            description: string;
            /** Knowledge Point Ids */
            knowledge_point_ids: string[];
            /** Prerequisite Ids */
            prerequisite_ids?: string[];
            /** Resource Ids */
            resource_ids: string[];
            status: components["schemas"]["TaskStatus"];
            /** Task Id */
            task_id: string;
            task_type: components["schemas"]["TaskType"];
            /** Title */
            title: string;
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "foundation" | "protocol_analysis" | "case_study" | "innovation_challenge" | "project_practice" | "troubleshooting";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_events_api_v1_events_get: {
        parameters: {
            query?: {
                course_id?: string | null;
                user_id?: string | null;
                event_type?: components["schemas"]["EventType"] | null;
                object_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_api_v1_feedback_get: {
        parameters: {
            query?: {
                course_id?: string | null;
                user_id?: string | null;
                request_id?: string | null;
                status?: components["schemas"]["FeedbackStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerFeedback"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerFeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_api_v1_feedback__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_feedback_api_v1_feedback__feedback_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_changes_api_v1_knowledge_base_changes_get: {
        parameters: {
            query?: {
                course_id?: string | null;
                feedback_id?: string | null;
                change_status?: components["schemas"]["KnowledgeBaseChangeStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseChangeTask"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_change_api_v1_knowledge_base_changes__change_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseChangeTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_change_api_v1_knowledge_base_changes__change_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseChangeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseChangeTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_points_api_v1_knowledge_points_get: {
        parameters: {
            query?: {
                /** @description 按章节过滤 */
                chapter?: string | null;
                /** @description 按父知识点过滤 */
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_point_api_v1_knowledge_points__knowledge_point_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_point_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_api_v1_qa_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description 请求不符合接口契约 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_reviews_api_v1_quality_reviews_get: {
        parameters: {
            query?: {
                chunk_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReview"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_quality_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_v1_quality_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_api_v1_resources_get: {
        parameters: {
            query?: {
                course_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_resource_api_v1_resources_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_and_parse_api_v1_resources_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_and_parse_api_v1_resources_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resource_chunks_api_v1_resources__resource_id__chunks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkMetadata"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                /** @description 按任务状态过滤 */
                status?: components["schemas"]["TaskStatus"] | null;
                /** @description 按六类任务类型过滤 */
                task_type?: components["schemas"]["TaskType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTemplate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_status_api_v1_tasks__task_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
